version: '3'

networks:
    
    nginx-php-node-mariadb-redis:

services:
    #    jenkins-service:
    #        build:
    #            context: .
    #            dockerfile: ./jenkins/Dockerfile
    #        container_name: jenkins-container
    #        ports:
    #            - "8080:8080"
    #        #            - "50000:50000"
    #        volumes:
    #            - ./jenkins/jenkins_home:/var/jenkins_home
    #        networks:
    #            - nginx-php-node-mariadb-redis
    
    # mailchatcher
    mailer-service:
        image: schickling/mailcatcher
        container_name: mailer-container
        ports: [ 1025, 1080 ]
        networks:
            - nginx-php-node-mariadb-redis
    
    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-service
            - mariadb-service
        networks:
            - nginx-php-node-mariadb-redis
    
    # php
    php-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        #        ports:
        #            - "9000:9000"
        volumes:
            - ./app:/var/www/project
            - ./cache/symfony:/var/www/project/var/cache
            - ./logs/symfony:/var/www/project/var/log
        networks:
            - nginx-php-node-mariadb-redis
    
    # mariadb
    mariadb-service:
        image: mariadb:10.5.9
        #        build:
        #            context: .
        #            dockerfile: ./mariadb/Dockerfile
        container_name: mariadb-container
        ports:
            - "3306:3306"
        volumes:
            - ./db-data/mariadb:/var/lib/mysql
        #            - ./mariadb/conf.d:/etc/mysql/conf.d
        networks:
            - nginx-php-node-mariadb-redis
        restart: on-failure
        #        command: --read-buffer-size=16M --innodb-buffer-pool-size=16G --innodb_log_file_size=2G --net-read-timeout=90 --net-write-timeout=90 --key-buffer=128M --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-allowed-packet=500M --wait-timeout=2147483 --interactive-timeout=2147483 --log-warnings=4 --open-files-limit=100000 --connect-timeout=30 --slave-net-timeout=3600
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
    # node
    node-service:
        #        image: node:latest
        build:
            context: .
            dockerfile: ./node/Dockerfile
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        #        working_dir: /var/www/project
        networks:
            - nginx-php-node-mariadb-redis
    
    # redis
    redis-service:
        image: redis:6.2.2
        container_name: redis-container
        #        ports:
        #            - "6379:6379"
        restart: on-failure
        networks:
            - nginx-php-node-mariadb-redis