parameters:
    adminTo: '%env(MAILER_TO)%'
    adminFrom: '%env(MAILER_FROM)%'
    projectDir: '%kernel.project_dir%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]
    App\Service\TokenGenerator: ~
    App\Service\FileHandler\FileUploader:
        arguments:
            $projectDir: '%projectDir%'
    App\Service\Mailer:
        arguments:
            $adminTo: '%adminTo%'
            $adminFrom: '%adminFrom%'
