parameters:
    adminTo: '%env(MAILER_TO)%'
    adminFrom: '%env(MAILER_FROM)%'
    projectDir: '%kernel.project_dir%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]
    App\EventSubscriber\Entity\SoftDeleteSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App\EventSubscriber\Doctrine\EnableFilterListener:
        arguments:
            $em: '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    App\Service\TokenGenerator: ~
    App\Service\FileHandler\FileUploader:
        arguments:
            $projectDir: '%projectDir%'
    App\Service\Mailer:
        arguments:
            $adminTo: '%adminTo%'
            $adminFrom: '%adminFrom%'
