framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    
    session:
        handler_id: null
#        handler_id: 'session.handler.native_file'
#        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 18000
        cookie_secure: true
        cookie_httponly: true
    
    php_errors:
        log: true
    
    validation:
        enabled: true
        enable_annotations: true
